### ISSUE TITLE
osxcollector.output_filters.exceptions.MissingConfigError

### ISSUE THREAD

**Issue by gandg** [Yelp/osxcollector#100]
Hit this problem when running tool:
```shell
python -m osxcollector.output_filters.analyze -i osxcollector/osxcollect-2015_09_09-10_51_38/osxcollect-2015_09_09-10_51_38.json
```

**Comment by megancarney** [comment]
Have you followed the 'Filter configuration' section of the manual? osxcollector looks at a file called osxcollector.yaml for its configuration, and if it's not there, it will show you this error.

**Comment by gandg** [comment]
Thank you that helped.  I tried several other less ambitious filters, just the simple virus check one, and it failed with all kinds of errors after verifying my virus total key was in the yaml file.  I am disappointed as the tool looked promising, but may not be that user friendly to experiment with.  Perhaps a section on simple filter use ought to be added, like "grep the json output for all app start up apps", grep json file for list suspicious files installed.

**Comment by megancarney** [comment]
Do you have any jq commands you liked for the virustotal output? Would be easy to add. Also, what kind of errors are you seeing?

**Comment by jjsendor** [comment]
Closing this issue as there isn't enough details here.
