### ISSUE TITLE
Missing cffi in requirements-dev.txt

### ISSUE THREAD

**Issue by valsjo** [Yelp/osxcollector#131]
Tried to setup a virtualenv, but I couldn't get one of the commands to work (following the instructions in the README file).
When I tried:
        $pip install -r ./requirements-dev.txt
it's complaining about xattr

At least on my Mac OS X 10.11.3 I'm missing cffi which I added before xattr in the requirements-dev.txt file. Now it works.

**Comment by piax93** [comment]
Now the requirements-dev.txt also imports requirements.txt, so the issue should be solved.
