### ISSUE TITLE
"ImportError: No module named Foundation" due to Python installation via brew

### ISSUE THREAD

**Issue by jjsendor** [Yelp/osxcollector#134]
The issue is caused by the user installing their own version of Python via brew. By specifying the path of the builtin Python (`/usr/bin/python`) the script ran successfully.

OSXCollector should specifically test which Python version is being used.

**Comment by 0xdabbad00** [comment]
This can be fixed by catching the ImportErrror exception and if it's for Foundation, then inform the user that they need to use the full python path.

**Comment by piax93** [comment]
Added `pyobjc` to setup requirements.
