### ISSUE TITLE
python: can't open file 'osxcollector.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by PAULABAILEN** [Yelp/osxcollector#137]
I tried installing it on my Mac Terminal, sudo python osxcollector.py

python: can't open file 'osxcollector.py': [Errno 2] No such file or directory

**Comment by jjsendor** [comment]
@PAULABAILEN `osxcollector.py` script is in `osxcollector/` directory. So if you have just cloned the whole repository, you'll need to include that directory in the file path when executing OSXCollector.

In that case you should run it as:
```shell
$ sudo python osxcollector/osxcollector.py
```

**Comment by PAULABAILEN** [comment]
Hello,

Thank you for replying. I also want to clarify if this program can help me
with a litigation case.

Can this program generate history, web browser, url, timestamp from January
2014 - December 2014?

If so, please see the errors that I've been experiencing.

1. First, I had copied sudo python osxcollector/osxcollector.py and I got
an error:

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python:
can't open file 'osxcollector/osxcollector.py': [Errno 2] No such file or
directory

2. Then I tried the original script, sudo: osxcollector.py:
sudo: osxcollector.py: command not found

3. Finally, I tried
/Users/jimmypaula/Downloads/osxcollector-master/osxcollector/osxcollector.py

JAIMEs-MacBook-Pro% sudo
/Users/jimmypaula/Downloads/osxcollector-master/osxcollector/osxcollector.py

Password:
Traceback (most recent call last):
  File
"/Users/jimmypaula/Downloads/osxcollector-master/osxcollector/osxcollector.py",
line 41, in <module>
    import macholib.MachO
ImportError: No module named macholib.MachO


Thanks for all your help.

Paula

**Comment by jjsendor** [comment]
Hi @PAULABAILEN,
from the file paths you have copy-pasted it seems that you are using brew on your Mac machine and the Python installation that was installed via brew.

Could you try original Python interpreter that comes with Mac OS X?

To do that, invoke OSXCollector as following (assuming that you are inside the cloned GitHub repository):
```shell
$ sudo /usr/local/bin/python osxcollector/osxcollector.py
```

Hope that helps!

**Comment by PAULABAILEN** [comment]
Hello,

I tried your suggestion, and I got an error message again:

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python:
can't open file 'osxcollector/osxcollector.py': [Errno 2] No such file or
directory

I also tried the following:

sudo python
/Users/jimmypaula/Desktop/OSXForensics/osxcollector/osxcollector.py

Traceback (most recent call last):
  File
"/Users/jimmypaula/Desktop/OSXForensics/osxcollector/osxcollector.py", line
41, in <module>
    import macholib.MachO
ImportError: No module named macholib.MachO

Thanks. Paula

**Comment by PAULABAILEN** [comment]
Hello,

Furthermore, here's my repo:

https://github.com/PAULABAILEN/osxcollector.git

**Comment by jjsendor** [comment]
@PAULABAILEN, could paste here what do you see when you run `which python`?

It seems that you still use Python version managed by brew, that's why it cannot find Mac OS X-specific libraries.

**Comment by PAULABAILEN** [comment]
JAIMEs-MacBook-Pro% which python
/usr/local/bin/python
JAIMEs-MacBook-Pro% python --version
Python 2.7.11

**Comment by jjsendor** [comment]
@PAULABAILEN I might have been mistaken. I think `/usr/local/bin/python` is actually where brew installs Python and `/usr/bin/python` is the original location, at least looking at #134.

Could you try:
```shell
$ sudo /usr/bin/python osxcollector/osxcollector.py
```

and tell me if it works?

**Comment by PAULABAILEN** [comment]
I got the same issues. I did change and updated to Python 3. Will the
coding be different?

Thanks. Paula

**Comment by jjsendor** [comment]
I'd suggest using the default version of Python on OS X (2.7).

**Comment by PAULABAILEN** [comment]
Hello,

JAIMEs-MacBook-Pro% cd osxcollector
JAIMEs-MacBook-Pro% sudo /usr/bin/python2.7 osxcollector.py
Password:
[ERROR] Unable to parse plist: [The data couldn’t be read because it isn’t in the correct format.]. plist_path[/Applications/Adobe After Effects CS5/Plug-ins/Effects/Foundry/KeylightPro.plugin/Contents/Info.plist] - {'osxcollector_incident_id': 'osxcollect-2016_05_26-16_03_34', 'osxcollector_subsection': 'applications', 'osxcollector_section': 'applications'}

**Comment by PAULABAILEN** [comment]
[ERROR] Unable to parse plist: [The data couldn’t be read because it isn’t in the correct format.]. plist_path[/Applications/Adobe After Effects CS5/Plug-ins/Effects/Foundry/KeylightPro.plugin/Contents/Info.plist] - {'osxcollector_incident_id': 'osxcollect-2016_05_26-16_03_34', 'osxcollector_subsection': 'applications', 'osxcollector_section': 'applications'}
[ERROR] failed _log_sqlite_table near "1": syntax error <class 'sqlite3.OperationalError'> [('osxcollector.py', 1308, '_log_sqlite_table', "cursor.execute('SELECT * from {0}'.format(table_name))")] - {'osxcollector_table_name': u'1', 'osxcollector_incident_id': 'osxcollect-2016_05_26-16_03_34', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Firefox/Profiles/6oyn5a5a.default-1460806269425/places.sqlite', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'history', 'osxcollector_section': 'firefox'}
[ERROR] failed _log_sqlite_table database disk image is malformed <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1309, '_log_sqlite_table', 'rows = cursor.fetchall()')] - {'osxcollector_table_name': u'moz_historyvisits', 'osxcollector_incident_id': 'osxcollect-2016_05_26-16_03_34', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Firefox/Profiles/zqowk87w.default-1461982128860/places.sqlite', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'history', 'osxcollector_section': 'firefox'}
[ERROR] failed _log_sqlite_table near "1": syntax error <class 'sqlite3.OperationalError'> [('osxcollector.py', 1308, '_log_sqlite_table', "cursor.execute('SELECT * from {0}'.format(table_name))")] - {'osxcollector_table_name': u'1', 'osxcollector_incident_id': 'osxcollect-2016_05_26-16_03_34', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Firefox/Profiles/zqowk87w.default-1461982128860/places.sqlite', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'history', 'osxcollector_section': 'firefox'}

**Comment by jjsendor** [comment]
Hi @PAULABAILEN,
thanks for reporting these errors!

As answered in https://github.com/Yelp/osxcollector/issues/140#issuecomment-221995058 these errors indicate problems with reading some particular files but should not prevent OSXCollector from finishing the collection and writing the output file.

One of the reasons that comes to my mind is that the file OSXCollector tries to read from is empty (this happened sometime before, e.g. when Safari history is blank: #117). It's hard to tell for me what the problem could be here as I do not have the access to the files on which this fails.

Hopefully the information already collected from other sources on the disk satisfies your needs.

**Comment by mikechen66** [comment]
Thank a lot for jjsendor. I test that that my code works well in Mac Terminal with MacPorts according to the  direction. For instance, the command of sudo python3.5 hello/helloworld.py is ok. But I am wondering that Princeton has a practice of  pythonX.Y helloworld.py to run the program. But it fails.

**Comment by mikechen66** [comment]
ShadowRanger has an answer: It looks like you're running in IDLE; IDLE maintains its own pseudo-terminal, and that pseudo-terminal is not actually based on "real" files (something for which a kernel file descriptor exists). As such, it has no fileno to get; use a plain shell, not an IDE shell if you want fileno to work.

Please see the stackoverflow weblink: https://stackoverflow.com/questions/44123116/in-python-error-on-sys-stdin-fileno
