### ISSUE TITLE
Output Location

### ISSUE THREAD

**Issue by tonykustwan** [Yelp/osxcollector#145]
Is there a way too add a switch to specify which directory to place and tar the output.  Currently it places the output in /root.

Thanks

**Comment by jjsendor** [comment]
Hi @tonykustwan!
OSXCollector should place the output in the current directory (i.e. the directory when you are running the script).

You can change the output file name prefix with `-i`.

Hope that'll help!

**Comment by tonykustwan** [comment]
Any way to change the current directory?
