### ISSUE TITLE
[ERROR] failed _log_sqlite_db file is encrypted or is not a database.

### ISSUE THREAD

**Issue by PAULABAILEN** [Yelp/osxcollector#146]
[ERROR]   <type 'exceptions.UnicodeDecodeError'> [('osxcollector.py', 811, 'log_dict', 'cls.output_file.write(dumps(record))'), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py', 243, 'dumps', 'return _default_encoder.encode(obj)'), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 207, 'encode', 'chunks = self.iterencode(o, _one_shot=True)'), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 270, 'iterencode', 'return _iterencode(o, 0)')] - {'osxcollector_table_name': u'server_addresses', 'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Google/Chrome/Default/Web Data', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'web_data', 'osxcollector_section': 'chrome'}
[ERROR] failed _log_sqlite_table Could not decode to UTF-8 column 'id' with text '?Ⴢt?' <class 'sqlite3.OperationalError'> [('osxcollector.py', 1308, '_log_sqlite_table', "cursor.execute('SELECT * from {0}'.format(table_name))")] - {'osxcollector_table_name': u'server_addresses', 'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Google/Chrome/Default/Web Data', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'web_data', 'osxcollector_section': 'chrome'}
[ERROR]   <type 'exceptions.UnicodeDecodeError'> [('osxcollector.py', 811, 'log_dict', 'cls.output_file.write(dumps(record))'), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py', 243, 'dumps', 'return _default_encoder.encode(obj)'), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 207, 'encode', 'chunks = self.iterencode(o, _one_shot=True)'), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py', 270, 'iterencode', 'return _iterencode(o, 0)')] - {'osxcollector_table_name': u'server_address_metadata', 'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Google/Chrome/Default/Web Data', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'web_data', 'osxcollector_section': 'chrome'}
[ERROR] failed _log_sqlite_table Could not decode to UTF-8 column 'id' with text '?Ⴢt?' <class 'sqlite3.OperationalError'> [('osxcollector.py', 1308, '_log_sqlite_table', "cursor.execute('SELECT * from {0}'.format(table_name))")] - {'osxcollector_table_name': u'server_address_metadata', 'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Google/Chrome/Default/Web Data', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'web_data', 'osxcollector_section': 'chrome'}
[ERROR] failed _log_sqlite_table near "1": syntax error <class 'sqlite3.OperationalError'> [('osxcollector.py', 1308, '_log_sqlite_table', "cursor.execute('SELECT * from {0}'.format(table_name))")] - {'osxcollector_table_name': u'1', 'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Firefox/Profiles/6oyn5a5a.default-1460806269425/places.sqlite', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'history', 'osxcollector_section': 'firefox'}
[ERROR] failed _log_sqlite_table database disk image is malformed <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1309, '_log_sqlite_table', 'rows = cursor.fetchall()')] - {'osxcollector_table_name': u'moz_historyvisits', 'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Firefox/Profiles/q0i9iudp-1.default-1388257208645/places.sqlite', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'history', 'osxcollector_section': 'firefox'}
[ERROR] failed _log_sqlite_table near "1": syntax error <class 'sqlite3.OperationalError'> [('osxcollector.py', 1308, '_log_sqlite_table', "cursor.execute('SELECT * from {0}'.format(table_name))")] - {'osxcollector_table_name': u'1', 'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Firefox/Profiles/q0i9iudp-1.default-1388257208645/places.sqlite', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'history', 'osxcollector_section': 'firefox'}
[ERROR] failed _log_sqlite_table database disk image is malformed <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1309, '_log_sqlite_table', 'rows = cursor.fetchall()')] - {'osxcollector_table_name': u'moz_historyvisits', 'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Firefox/Profiles/zqowk87w.default-1461982128860/places.sqlite', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'history', 'osxcollector_section': 'firefox'}
[ERROR] failed _log_sqlite_table near "1": syntax error <class 'sqlite3.OperationalError'> [('osxcollector.py', 1308, '_log_sqlite_table', "cursor.execute('SELECT * from {0}'.format(table_name))")] - {'osxcollector_table_name': u'1', 'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Application Support/Firefox/Profiles/zqowk87w.default-1461982128860/places.sqlite', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'history', 'osxcollector_section': 'firefox'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/http_c.betrad.com_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/http_cdn.cxense.com_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/http_pushmobile.abs-cbn.com_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/http_www.pshsa.ca_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/http_www.sportinglife.ca_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/http_www.workopolis.com_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/https_abinbev.taleo.net_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/https_cfl.dropboxstatic.com_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/https_decoding.wordpress.com_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/https_icfi.taleo.net_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/https_jobs.bce.ca_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/https_jobs.hatch.com_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/https_manulife.taleo.net_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/https_pcl.taleo.net_0.localstorage-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}
[ERROR] failed _log_sqlite_db file is encrypted or is not a database <class 'sqlite3.DatabaseError'> [('osxcollector.py', 1349, '_log_sqlite_db', 'self._raw_log_sqlite_db(sqlite_db_path)'), ('osxcollector.py', 1328, '_raw_log_sqlite_db', 'cursor.execute(\'SELECT * from sqlite_master WHERE type = "table"\')')] - {'osxcollector_incident_id': 'osxcollect-2017_01_17-00_50_55', 'osxcollector_db_path': '/Users/jimmypaula/Library/Safari/LocalStorage/StorageTracker.db-shm', 'osxcollector_username': 'jimmypaula', 'osxcollector_subsection': 'localstorage', 'osxcollector_section': 'safari'}

**Comment by jjsendor** [comment]
Hi @PAULABAILEN! Thank you for reporting this. Similarly to #147 these errors shouldn't cause OSXCollector to crash and they are just mere indicators of some part of the forensic information being not available for collection.
