### ISSUE TITLE
Ability to run against a mounted disk image or target disk mode mac

### ISSUE THREAD

**Issue by Coros** [Yelp/osxcollector#148]
I've always been told to work against disk images and never a live machine.  This doesn't appear possible with this tool.  I currently do most of the work by hand and was looking for an automated way to gather the information but I'm unable to run this tool against a disk image.  

edit: I see I can modify the root path variable but it would be nice if the tool prompted for it.

**Comment by jjsendor** [comment]
Hi @Coros!
Since OSXCollector was designed to run as a standalone script, it does not prompt for any parameters but they can be supplied in a command line.

As you have observed, you can run it against a mounted disk drive with `-p ROOTPATH/--path=ROOTPATH` option.

I hope that help.
