### ISSUE TITLE
Missing Info on Dependencies

### ISSUE THREAD

**Issue by sroberts** [Yelp/osxcollector#17]
Working directly off the instructions on the wiki starting up osxcollector on a new 10.10 machine led to a number of errors related to missing Python dependencies. 

Specifically I needed to run: `sudo pip install xattr pyobjc`

This may be confusing to new users. Since most of the documentation is in the wiki would you want that information in there or as something added to the README? I'm happy to submit a PR if I can.

**Comment by x44x45x41x4E** [comment]
Hmmmnnn. I've had this issue now. I still need to install both dependencies. Using ZSH on my iTerm and installed python via homebrew. If you need any more info about my machine's current setup, let me know. I'm not familliar with Python that much so I must be missing something. It did work after installing both depedencies with some errors though (I'll look up those errors first before opening an issue or asking).

Thanks.
