### ISSUE TITLE
1.11 doesn't run?

### ISSUE THREAD

**Issue by zestysoft** [Yelp/osxcollector#171]
$ sudo python osxcollector/osxcollector.py

> Traceback (most recent call last):
>   File "osxcollector/osxcollector.py", line 48, in <module>
>     from osxcollector import __version__
>   File "/Users/User/Downloads/osxcollector-1.11/osxcollector/osxcollector.py", line 48, in <module>
>     from osxcollector import __version__
> ImportError: cannot import name __version__

**Comment by piax93** [comment]
I moved the `__version__` definition away from the main file in the attempt of making the package buildable on systems different from MacOS. Thinking again about it, this violates a bit the single-script-philosophy, so I'll try to find an alternate solution.

**Comment by piax93** [comment]
This was addressed in 3ebf162
