### ISSUE TITLE
Add OSXCollector to pip

### ISSUE THREAD

**Issue by ivanlei** [Yelp/osxcollector#39]
It would be nice if people could `pip install osxcollector`

**Comment by jjsendor** [comment]
There is a section on the site linked by ikoniaris that lists all the steps necessary to upload a project to PyPI:
https://python-packaging-user-guide.readthedocs.org/en/latest/distributing.html#uploading-your-project-to-pypi

**Comment by jjsendor** [comment]
OSXCollector is now available on PyPI: https://pypi.python.org/pypi/osxcollector
