### ISSUE TITLE
[ERROR] failed section 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by deweydb** [Yelp/osxcollector#55]
[ERROR] failed section 'str' object has no attribute 'get' <type 'exceptions.AttributeError'> [('osxcollector.py', 574, 'collect', 'collection_method()'), ('osxcollector.py', 1113, '_collect_applications', "self._log_packages_in_dir(pathjoin(ROOT_PATH, 'Applications'))"), ('osxcollector.py', 711, '_log_packages_in_dir', "cfbundle_executable = plist.get('CFBundleExecutable')")] - {'osxcollector_incident_id': 'osxcollect-2015_01_12-16_05_41', 'osxcollector_section': 'applications'}

**Comment by ivanlei** [comment]
Interesting. Seems like somehow `_read_plist` isn't returning a dict.
I can add some specific error handling for this and hopefully we'll be able to figure out what's up.

**Comment by ivanlei** [comment]
This should be fixed.
The ERROR should be non-fatal now and give info about which file it couldn't properly read.
