### ISSUE TITLE
Add whitelist support to virustotal.LookupUrlsFilter

### ISSUE THREAD

**Issue by ivanlei** [Yelp/osxcollector#84]
Looking up all of the URLs in the osxcollector output might cause some sensitive data to be send to VirusTotal.

Let's follow what we are doing with the domains in LookupDomainsFilter and not look up the reports for the whitelisted stuff.

**Comment by jjsendor** [comment]
Migrated to https://github.com/Yelp/osxcollector_output_filters/issues/3
