### ISSUE TITLE
Ignore adblock_custom field value when discovering domains in find_domains filter

### ISSUE THREAD

**Issue by ivanlei** [Yelp/osxcollector#85]
Currently find_domains filter tries to extract domain names from any value.

_adblock_custom_ contains a lot of domains (not to mention that they are stored in just one big string) that are on the AdBlock's blacklist. It does not make sense to extract any domain names from this field as it could contain a lot of malware websites that user actually not visited.

This field is in _osxcollector_section_ *chrome* and _osxcollector_subsection_ *local_storage*. _osxcollector_table_name_ is *ItemTable*

I have tried to analyze _specificMalware_ and grepped for {{installmac}}.
It was found in that item and when I looked at how many domains were extracted from this single value (which apparently is the whole local storage of Chrome web browser) it was big:
```shell
$ cat foo.json | grep installmac | jq '.osxcollector_domains' | wc -l
     990
```

**Comment by jjsendor** [comment]
Migrated to https://github.com/Yelp/osxcollector_output_filters/issues/4
