### ISSUE TITLE
SSL errors when running analyze filter

### ISSUE THREAD

**Issue by megancarney** [Yelp/osxcollector#99]
Getting this when I run the analyze filter on my machine. I get the same errors on a fresh install of OS X (in a VM) with a fresh clone of osxcollector.
```
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
[ERROR] url[https://www.virustotal.com/vtapi/v2/file/report] status_code[<UNKNOWN>]
Traceback (most recent call last):
  File "/Users/<username>/osxcollector/venv_osxcollector2/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/<username>/osxcollector/venv_osxcollector2/lib/python2.7/site-packages/grequests.py", line 71, in send
    self.url, **merged_kwargs)
  File "/Users/<username>/osxcollector/venv_osxcollector2/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/<username>/osxcollector/venv_osxcollector2/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/<username>/osxcollector/venv_osxcollector2/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
<Greenlet at 0x11c74c730: <bound method AsyncRequest.send of <grequests.AsyncRequest object at 0x11c85bb90>>(stream=False)> failed with SSLError
```

pip freeze:
altgraph==0.12
aspy.yaml==0.2.1
backports.ssl-match-hostname==3.4.0.2
cached-property==1.2.0
certifi==2015.4.28
cffi==1.2.0
coverage==3.7.1
functools32==3.2.3.post2
gevent==1.0.2
greenlet==0.4.7
grequests==0.2.0
jsonschema==2.5.1
macholib==1.7
mock==1.0.1
modulegraph==0.12.1
nodeenv==0.13.3
ordereddict==1.1
pluggy==0.3.0
pre-commit==0.5.2
py==1.4.30
py2app==0.9
pycparser==2.14
pyflakes==0.9.1
pyobjc==3.0.4
pyobjc-core==3.0.4
pyobjc-framework-Accounts==3.0.4
pyobjc-framework-AddressBook==3.0.4
pyobjc-framework-AppleScriptKit==3.0.4
pyobjc-framework-AppleScriptObjC==3.0.4
pyobjc-framework-Automator==3.0.4
pyobjc-framework-CalendarStore==3.0.4
pyobjc-framework-CFNetwork==3.0.4
pyobjc-framework-Cocoa==3.0.4
pyobjc-framework-Collaboration==3.0.4
pyobjc-framework-CoreData==3.0.4
pyobjc-framework-CoreLocation==3.0.4
pyobjc-framework-CoreText==3.0.4
pyobjc-framework-CoreWLAN==3.0.4
pyobjc-framework-DictionaryServices==3.0.4
pyobjc-framework-DiskArbitration==3.0.4
pyobjc-framework-EventKit==3.0.4
pyobjc-framework-ExceptionHandling==3.0.4
pyobjc-framework-FSEvents==3.0.4
pyobjc-framework-InputMethodKit==3.0.4
pyobjc-framework-InstallerPlugins==3.0.4
pyobjc-framework-InstantMessage==3.0.4
pyobjc-framework-LatentSemanticMapping==3.0.4
pyobjc-framework-LaunchServices==3.0.4
pyobjc-framework-PreferencePanes==3.0.4
pyobjc-framework-PubSub==3.0.4
pyobjc-framework-QTKit==3.0.4
pyobjc-framework-Quartz==3.0.4
pyobjc-framework-ScreenSaver==3.0.4
pyobjc-framework-ScriptingBridge==3.0.4
pyobjc-framework-SearchKit==3.0.4
pyobjc-framework-ServiceManagement==3.0.4
pyobjc-framework-Social==3.0.4
pyobjc-framework-StoreKit==3.0.4
pyobjc-framework-SyncServices==3.0.4
pyobjc-framework-SystemConfiguration==3.0.4
pyobjc-framework-WebKit==3.0.4
PyYAML==3.11
requests==2.7.0
simplejson==3.7.3
six==1.9.0
SQLAlchemy==1.0.8
testify==0.7.2
threat-intel==0.1.3
tldextract==1.6
tornado==4.2.1
tox==2.0.2
virtualenv==13.1.0
wheel==0.24.0
xattr==0.7.8

$ python --version
Python 2.7.10
$ python -c 'import ssl; print ssl._OPENSSL_API_VERSION'
(0, 9, 8, 29, 15)

**Comment by megancarney** [comment]
Seems to be something in the virustotal code. If I run with --no-virustotal I get fewer errors.

**Comment by megancarney** [comment]
Recreated the issue on a pre-Yosemite OS X laptop with a fresh clone of osxcollector

**Comment by jjsendor** [comment]
Hi @megancarney,
can you try if you get the same error when using https://github.com/Yelp/threat_intel directly?

**Comment by megancarney** [comment]
This code works without errors in the same virtualenv:
import requests
from threat_intel.virustotal import VirusTotalApi

vt = VirusTotalApi("<api_key>", resources_per_req=25)
domains = ["google.com", "baidu.com", "bibikun.ru"]
vt.get_domain_reports(domains)
urls = ["http://www.google.com", "http://www.yelp.com"]
vt.get_url_reports(urls)
file_hashes = [
    "99017f6eebbac24f351415dd410d522d",
    "88817f6eebbac24f351415dd410d522d"
]

vt.get_file_reports(file_hashes)

file_hashes = ['<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>','<hash>']
vt.get_file_reports(file_hashes)

**Comment by jjsendor** [comment]
I am wondering if it might be due to hitting the limits on VirusTotal API.

**Comment by megancarney** [comment]
I don't think it's the rate limit, as the first request with a batch of 25 file hashes often fails. AFAIK, the rate limit doesn't apply to our private API key. The other reason I suspect it's not the rate limiting is that a retry immediately after the failed request often works.

I suspect this could be the problem, but I tried to get that solution working in the code and couldn't: http://stackoverflow.com/questions/21978115/using-grequests-to-make-several-thousand-get-requests-to-sourceforge-get-max-r.

This terrible, terrible hack seems to make things work for now:
/greenlet.py
320a321,322
>         #import pdb
>         #pdb.set_trace()
327c329,338
<                 result = self._run(*self.args, **self.kwargs)
---
>                 # a terrible hack to deal with the SSL errors I've been seeing
>                 retry = 0
>                 max_retry = 10
>                 result = None
>                 while retry <= max_retry and result is None:
>                   try:
>                     retry = retry + 1
>                     result = self._run(*self.args, **self.kwargs)
>                   except:
>                     pass

**Comment by megancarney** [comment]
Okay, I think I found the root cause:
https://github.com/shazow/urllib3/blob/master/urllib3/connectionpool.py

The version of urllib bundled with requests (at least on my machine) raises a type exception error as it's trying to raise an SSL error, which leads to odd things happening. Like a response object that is entirely empty.

**Comment by megancarney** [comment]
Submitting a pull request to the threat_intel library.
